# kate: indent-width 2;

clone_depth: 1

environment:
  matrix:
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TARGET: desktop
    COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TARGET: desktop-gles
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TARGET: desktop-gles
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TARGET: rt
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TARGET: rt
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TARGET: rt
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TARGET: rt
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- cinst ninja
- set PATH=C:/Sys/bin;C:/tools/ninja;%PATH%
# `cinst mingw` fails with 404 since Dec 2016, `appveyor Downloadfile` fails
# with "Message string length exceeds 32k characters" so I have to call a
# fucking powershell command in order to download a file. Oh and %20 in the URL
# somehow gives a 404 ALSO so I have to explicitly use spaces. WHAT THE FUCK!
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z powershell -Command "(new-object System.Net.WebClient).Downloadfile('https://sourceforge.net/projects/mingw-w64/files/Toolchains targetting Win64/Personal Builds/mingw-builds/6.3.0/threads-posix/seh/x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z', 'x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z')"
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" cd C:\tools && 7z x %APPVEYOR_BUILD_FOLDER%\x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z && cd %APPVEYOR_BUILD_FOLDER%

# OVR SDK
- IF "%TARGET%" == "desktop" set DO_OVR=1
- IF "%TARGET%" == "desktop-gles" set DO_OVR=1
- IF "%DO_OVR%" == "1" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\ovr_sdk_win_1.15.0_public.zip appveyor DownloadFile https://securecdn.oculus.com/binaries/download/?id=1404281146296633^&access_token=OC%7C1196467420370658%7C
- IF "%DO_OVR%" == "1" 7z x ovr_sdk_win_1.15.0_public.zip -o%APPVEYOR_BUILD_FOLDER%\deps

build_script:
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" call package\ci\appveyor-desktop.bat
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" call package\ci\appveyor-desktop-mingw.bat
- IF "%TARGET%" == "desktop-gles" call package\ci\appveyor-desktop-gles.bat
- IF "%TARGET%" == "rt" call package\ci\appveyor-rt.bat

cache:
- ovr_sdk_win_1.15.0_public.zip -> package/ci/appveyor-cache-reset.txt
- x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z -> package/ci/appveyor-cache-reset.txt
- 2.86.1.zip -> package/ci/appveyor-cache-reset.txt
