# kate: indent-width 2;

clone_depth: 1

environment:
  matrix:
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-gl-msvc2015
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gl-msvc2017
  - TARGET: desktop
    COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gl-mingw
  - TARGET: desktop-gles
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-gles2-msvc2015
  - TARGET: desktop-gles
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gles2-msvc2017
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-gles3-msvc2015
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gles3-msvc2017
  - TARGET: rt
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-rt-gles2-msvc2015
  - TARGET: rt
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-rt-gles2-msvc2017
  - TARGET: rt
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-rt-gles3-msvc2015
  - TARGET: rt
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-rt-gles3-msvc2017

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- cinst ninja
- set PATH=C:/Sys/bin;C:/tools/ninja;%PATH%
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" pip install codecov

# GLM
- IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\0.9.9.0.zip appveyor DownloadFile https://github.com/g-truc/glm/archive/0.9.9.0.zip
- 7z x 0.9.9.0.zip -o%APPVEYOR_BUILD_FOLDER%\deps && ren %APPVEYOR_BUILD_FOLDER%\deps\glm-0.9.9.0 glm

# OVR SDK
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\ovr_sdk_win_1.26.0_public_minimal.zip appveyor DownloadFile http://ci.magnum.graphics/ovr_sdk_win_1.26.0_public_minimal.zip
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" 7z x ovr_sdk_win_1.26.0_public_minimal.zip -o%APPVEYOR_BUILD_FOLDER%\deps

build_script:
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" call package\ci\appveyor-desktop.bat
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" call package\ci\appveyor-desktop-mingw.bat
- IF "%TARGET%" == "desktop-gles" call package\ci\appveyor-desktop-gles.bat
- IF "%TARGET%" == "rt" call package\ci\appveyor-rt.bat

cache:
- ovr_sdk_win_1.26.0_public_minimal.zip -> package/ci/appveyor-cache-reset.txt
- 2.86.1.zip -> package/ci/appveyor-cache-reset.txt
